/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.fruitbowl;

import org.testng.annotations.*;

import java.util.Arrays;

import static org.testng.Assert.*;

public class AppTest {
    @Test
    public void segregateFruitsByName() {

        Bowl allFruitBowl = new Bowl();
        allFruitBowl.addAll(Arrays.asList(
                new Fruit("Apple", "Red", "Sweet", "Medium"),
                new Fruit("Apple", "Green", "Sour", "Small"),
                new Fruit("Grapes", "Green", "Sour", "Small"),
                new Fruit("Orange", "Orange", "Sour", "Medium"),
                new Fruit("Orange", "Yellow", "Sweet", "Medium"),
                new Fruit("Banana", "Yellow", "Sweet", "Large"),
                new Fruit("Kiwi", "Grey", "Sour", "Medium")
        ));

        MultilayerBasket basket = new MultilayerBasket(allFruitBowl);
        basket.segregateFruitsByName();
        System.out.println("----Segregate By Name----");
        for (Bowl bowl : basket.getBowls()) {
            System.out.print(bowl.getFruits().toString());
            System.out.println();
        }
    }

    @Test
    public void segregateFruitsByColour() {

        Bowl allFruitBowl = new Bowl();
        allFruitBowl.addAll(Arrays.asList(
                new Fruit("Apple", "Red", "Sweet", "Medium"),
                new Fruit("Apple", "Green", "Sour", "Small"),
                new Fruit("Grapes", "Green", "Sour", "Small"),
                new Fruit("Orange", "Orange", "Sour", "Medium"),
                new Fruit("Orange", "Yellow", "Sweet", "Medium"),
                new Fruit("Banana", "Yellow", "Sweet", "Large"),
                new Fruit("Kiwi", "Grey", "Sour", "Medium")
        ));

        MultilayerBasket basket = new MultilayerBasket(allFruitBowl);
        basket.segregateFruitsByColour();
        System.out.println("----Segregate By Colour----");
        for (Bowl bowl : basket.getBowls()) {
            System.out.print(bowl.getFruits().toString());
            System.out.println();
        }
    }@Test
    public void segregateFruitsByType() {

        Bowl allFruitBowl = new Bowl();
        allFruitBowl.addAll(Arrays.asList(
                new Fruit("Apple", "Red", "Sweet", "Medium"),
                new Fruit("Apple", "Green", "Sour", "Small"),
                new Fruit("Grapes", "Green", "Sour", "Small"),
                new Fruit("Orange", "Orange", "Sour", "Medium"),
                new Fruit("Orange", "Yellow", "Sweet", "Medium"),
                new Fruit("Banana", "Yellow", "Sweet", "Large"),
                new Fruit("Kiwi", "Grey", "Sour", "Medium")
        ));

        MultilayerBasket basket = new MultilayerBasket(allFruitBowl);
        basket.segregateFruitsByType();
        System.out.println("----Segregate By Type----");
        for (Bowl bowl : basket.getBowls()) {
            System.out.print(bowl.getFruits().toString());
            System.out.println();
        }
    }@Test
    public void segregateFruitsBySize() {

        Bowl allFruitBowl = new Bowl();
        allFruitBowl.addAll(Arrays.asList(
                new Fruit("Apple", "Red", "Sweet", "Medium"),
                new Fruit("Apple", "Green", "Sour", "Small"),
                new Fruit("Grapes", "Green", "Sour", "Small"),
                new Fruit("Orange", "Orange", "Sour", "Medium"),
                new Fruit("Orange", "Yellow", "Sweet", "Medium"),
                new Fruit("Banana", "Yellow", "Sweet", "Large"),
                new Fruit("Kiwi", "Grey", "Sour", "Medium")
        ));

        MultilayerBasket basket = new MultilayerBasket(allFruitBowl);
        basket.segregateFruitsBySize();
        System.out.println("----Segregate By Size----");
        for (Bowl bowl : basket.getBowls()) {
            System.out.print(bowl.getFruits().toString());
            System.out.println();
        }
    }
}
